CREATE DATABASE mydb;
USE mydb;
-- EJERCICIO 1  --

CREATE TABLE IF NOT EXISTS curso (
  Cod_Curso INT(11) PRIMARY KEY  NOT NULL,
  Nombre VARCHAR(45),
  Cod_Matricula INT(11),
  id_Profesor INT(11)
);


CREATE TABLE IF NOT EXISTS alumno (
  Cod_Matricula INT(11) PRIMARY KEY  NOT NULL,
  Nombre VARCHAR(45) ,
  DNI INT(11) ,
  Fecha_Nacimiento DATE ,
  Email VARCHAR(45) ,
  Cod_Curso INT(11) 
);




CREATE TABLE IF NOT EXISTS profesor (
  id_Profesor INT(11) ,
  Nombre VARCHAR(45),
  Especialidad VARCHAR(45),
  Email VARCHAR(45) ,
  Cod_Curso INT(11) ,
  CONSTRAINT profesor_ibfk_1
    FOREIGN KEY (Cod_Curso)
    REFERENCES curso (Cod_Curso)
);

ALTER TABLE  curso 
ADD CONSTRAINT fkcurso_alumno FOREIGN KEY(Cod_Matricula) REFERENCES alumno(Cod_Matricula);

ALTER TABLE  alumno
ADD CONSTRAINT fkalumno_curso FOREIGN KEY(Cod_Curso) REFERENCES curso (Cod_Curso);

ALTER TABLE  profesor
ADD CONSTRAINT fkCurso_profesor FOREIGN KEY(Cod_Curso) REFERENCES curso (Cod_Curso);

-- EJERCICIO 1  --

-- EJERCICIO 2 --

CREATE TABLE IF NOT EXISTS PAIS (
  ID_Pais    INT PRIMARY KEY NOT NULL,
  Nombre_Pais VARCHAR(45) 
);
  



CREATE TABLE IF NOT EXISTS PROVINCIA (
  ID_Provincia  INT PRIMARY KEY NOT NULL,
  Nombre_Provincia VARCHAR(45) ,
  PAIS_ID_Pais INT NOT NULL
  
);


CREATE TABLE IF NOT EXISTS EMPLEADO (
  id_Empleado  INT PRIMARY KEY NOT NULL,
  DNI INT ,
  Nombre VARCHAR(45),
  Telefono VARCHAR(45) ,
  Email VARCHAR(45) ,
  Fecha_alta DATE 
  
);

CREATE TABLE IF NOT EXISTS LOCALIDAD (
 Codigo_Localidad INT  PRIMARY KEY  NOT NULL,
 Nombre VARCHAR(45) ,
 Codigo_Postal INT ,
 PROVINCIA_ID_Provincia INT NOT NULL,
 EMPLEADO_id_Empleado INT NOT NULL
 
);
    

ALTER TABLE  PROVINCIA
ADD CONSTRAINT `fk_PROVINCIA_PAIS1`
    FOREIGN KEY (`PAIS_ID_Pais`)
    REFERENCES `mydb`.`PAIS` (`ID_Pais`);


ALTER TABLE  LOCALIDAD
ADD CONSTRAINT fk_LOCALIDAD_PROVINCIA1
    FOREIGN KEY (PROVINCIA_ID_Provincia)
    REFERENCES PROVINCIA(ID_Provincia),
    
ADD CONSTRAINT fk_LOCALIDAD_EMPLEADO1
    FOREIGN KEY (EMPLEADO_id_Empleado)
    REFERENCES EMPLEADO(id_Empleado)
;


-- EJERCICIO 2 --
-- EJERCICIO 3 --

CREATE TABLE IF NOT EXISTS CLIENTES (
 id_Cliente INT PRIMARY KEY  NOT NULL,
 Nombre VARCHAR(45) ,
 DNI INT ,
 Direccion VARCHAR(45) ,
 Telefono VARCHAR(45) ,
 Aval INT 
);




CREATE TABLE IF NOT EXISTS RESERVAS (
id_Reserva INT PRIMARY KEY  NOT NULL,
Fecha_Inicio DATE ,
Fecha_Final DATE ,
Precio_Total DECIMAL ,
CLIENTES_id_Cliente INT NOT NULL

);



CREATE TABLE IF NOT EXISTS AUTOS(
  id_Auto INT PRIMARY KEY  NOT NULL,
  Patente VARCHAR(45), 
  Modelo VARCHAR(45), 
  Color VARCHAR(45),
  Marca VARCHAR(45),
  RESERVAS_id_Reserva INT NOT NULL,
  Precio DOUBLE
);


CREATE TABLE IF NOT EXISTS Detalles_Reserva(
 Litros DOUBLE,
 AUTOS_id_Auto INT PRIMARY KEY NOT NULL
);


ALTER TABLE RESERVAS
ADD CONSTRAINT `fk_RESERVAS_CLIENTES`
    FOREIGN KEY (`CLIENTES_id_Cliente`)
    REFERENCES `mydb`.`CLIENTES` (`id_Cliente`)
;

ALTER TABLE AUTOS
ADD CONSTRAINT `fk_AUTOS_RESERVAS1`
    FOREIGN KEY (`RESERVAS_id_Reserva`)
    REFERENCES `mydb`.`RESERVAS` (`id_Reserva`)
;

ALTER TABLE Detalles_Reserva
ADD CONSTRAINT `fk_Detalles_Reserva_AUTOS1`
    FOREIGN KEY (`AUTOS_id_Auto`)
    REFERENCES `mydb`.`AUTOS` (`id_Auto`)

-- EJERCICIO 3--

