-- Ejercicio 2   --
SELECT * FROM pedidos ORDER BY fecha DESC ;
SELECT * FROM pedidos ORDER BY cantidad DESC LIMIT 2;
SELECT Clientes.id FROM clientes, pedidos WHERE clientes.id = pedidos.id AND cantidad < 0 ;
SELECT c.id, c.nombre FROM Clientes c JOIN pedidos p ON c.id = p.id_cliente WHERE c.id = p.id_cliente GROUP BY id  ;
SELECT p.id, p.cantidad, p.fecha, p.id_cliente, p.id_vendedor FROM pedidos p JOIN clientes c ON c.id = p.id_cliente WHERE p.fecha LIKE "%2022%" AND p.cantidad > 500 ;
SELECT v.nombre, v.apellido FROM vendedores v WHERE v.comisión  < 0.11  AND    v.comisión  > 0.05;
SELECT v.comisión FROM vendedores v ORDER BY v.comisión DESC LIMIT 1 ; 
SELECT c.id, c.nombre, c.apellido FROM clientes c WHERE  c.cuitcuil != ""  ORDER BY c.nombre;
SELECT c.nombre FROM clientes c WHERE c.nombre LIKE "A%" "n%" OR c.nombre LIKE "P%"  ORDER BY c.nombre  ;
SELECT c.nombre FROM clientes c WHERE c.nombre LIKE "%el" OR  c.nombre LIKE   "%o" GROUP BY c.nombre;
SELECT c.id, c.nombre, c.apellido FROM Clientes c JOIN pedidos p ON c.id = p.id_cliente WHERE c.id = p.id_cliente GROUP BY id ORDER BY c.nombre ;
SELECT * FROM pedidos p JOIN clientes c ON p.id_cliente = c.id  ; 
SELECT * FROM pedidos p JOIN vendedores v ON v.id = p.id_vendedor ORDER BY v.nombre   ; 
SELECT * FROM pedidos p JOIN vendedores v ON v.id = p.id_vendedor JOIN clientes c ON p.id_cliente = c.id;
SELECT c.nombre FROM clientes c JOIN pedidos p ON c.id = p.id_cliente WHERE p.fecha LIKE "%2022%" AND p.cantidad > 30 AND p.cantidad < 100   ;
SELECT v.nombre, v.apellido FROM pedidos p JOIN vendedores v ON v.id = p.id_vendedor JOIN clientes c ON p.id_cliente = c.id WHERE p.id_cliente = c.id AND c.nombre = "María"    ;
SELECT c.nombre FROM pedidos p JOIN vendedores v ON v.id = p.id_vendedor JOIN clientes c ON p.id_cliente = c.id WHERE p.id_cliente = c.id AND v.nombre = "Daniel" GROUP BY c.nombre  ORDER BY c.nombre ;
SELECT c.id, concat(c.nombre, "_", c.apellido), p.cantidad, p.fecha, p.id_vendedor from clientes c left join pedidos p on c.id=p.id_cliente GROUP BY c.id order by c.nombre, c.apellido   ;
SELECT v.id, concat(v.nombre, "_", v.apellido), p.cantidad, p.fecha, p.id FROM vendedores v LEFT JOIN pedidos p ON v.id = p.id_vendedor GROUP BY p.id_vendedor ORDER BY v.nombre, v.apellido; 
SELECT  concat_ws(' ',c.nombre,c.apellido) FROM clientes c WHERE c.id NOT IN (SELECT p.id_cliente FROM pedidos p);
SELECT concat_ws(' ',v.nombre,v.apellido) FROM vendedores v WHERE v.id NOT IN (SELECT p.id_vendedor FROM pedidos p);
SELECT SUM(p.cantidad) FROM pedidos p;
SELECT AVG(p.cantidad) FROM pedidos p;
SELECT COUNT( distinct  p.id_vendedor) FROM pedidos p;
SELECT COUNT(c.id) FROM clientes c;
SELECT MAX(p.cantidad) FROM pedidos p;
SELECT MIN(p.cantidad) FROM pedidos p;
SELECT  c.ciudad, c.categoría FROM clientes c WHERE c.categoría != 0 GROUP BY c.ciudad  ORDER BY  c.categoría DESC   ;
SELECT MAX(pedidos.cantidad) AS Max_Pedido, fecha, id_cliente, clientes.nombre, clientes.apellido  FROM ventas.pedidos INNER JOIN ventas.clientes ON ventas.clientes.id=ventas.pedidos.id_cliente GROUP BY ventas.pedidos.id_cliente, ventas.pedidos.fecha;
SELECT MAX(pedidos.cantidad) AS Max_Pedido, fecha, id_cliente, clientes.nombre, clientes.apellido  FROM ventas.pedidos INNER JOIN ventas.clientes ON ventas.clientes.id=ventas.pedidos.id_cliente WHERE pedidos.cantidad > 2000 GROUP BY ventas.pedidos.id_cliente, ventas.pedidos.fecha;
SELECT  v.id, v.nombre, v.apellido, p.fecha, p.cantidad FROM vendedores v JOIN pedidos p ON v.id = p.id_vendedor WHERE fecha LIKE '2021-08-17' ORDER BY v.nombre, v.apellido;
SELECT c.id, c.nombre, c.apellido, COUNT(id_cliente) AS Total_Cant FROM pedidos p LEFT JOIN clientes c ON c.id = p.id_cliente GROUP BY c.id;
SELECT c.id, c.nombre, c.apellido, COUNT(id_cliente) AS Total_Cant FROM pedidos p LEFT JOIN clientes c ON c.id = p.id_cliente WHERE p.fecha LIKE "2020%" GROUP BY c.id;
SELECT p.id, MAX(p.cantidad) AS Max_Cantidad, YEAR(p.fecha) AS año FROM pedidos p GROUP BY YEAR(p.fecha) ORDER BY YEAR(p.fecha) ASC;
SELECT COUNT(p.cantidad) AS cantidad_total , YEAR(p.fecha) AS año FROM pedidos p GROUP BY YEAR(p.fecha)  ORDER BY YEAR(p.fecha) ASC; 
SELECT p.cantidad AS cantidad_pedidos, CONCAT_WS("_",c.nombre, c.apellido) AS nombre_cliente  FROM pedidos p LEFT JOIN clientes c ON p.id_cliente = c.id WHERE c.nombre = "adela";
SELECT p.cantidad AS cantidad_pedidos, CONCAT_WS("_",v.nombre, v.apellido) AS nombre_vendedor  FROM pedidos p LEFT JOIN vendedores v ON p.id_vendedor = v.id WHERE v.nombre = "Daniel";
SELECT *  FROM clientes c LEFT JOIN pedidos p ON p.id_cliente = c.id WHERE p.fecha LIKE "2020%"   ORDER BY p.cantidad DESC LIMIT 1;
SELECT p.fecha,  p.cantidad FROM pedidos p JOIN clientes c ON c.id = p.id_cliente WHERE c.nombre LIKE "Pepe" ORDER BY p.cantidad ASC LIMIT 1;
SELECT CONCAT(c.nombre, "", c.apellido) AS Cliente FROM clientes c WHERE c.id NOT IN ( SELECT p.id_cliente FROM pedidos p) ;
SELECT CONCAT(v.nombre, "", v.apellido) AS Vendedor FROM vendedores v WHERE v.id NOT IN ( SELECT p.id_vendedor FROM pedidos p) ;
SELECT CONCAT(c.nombre, " ", c.apellido) AS Cliente FROM clientes c WHERE NOT EXISTS ( SELECT p.id_cliente FROM pedidos p WHERE c.id = p.id_cliente  )  ;
SELECT CONCAT(v.nombre, "", v.apellido) AS Vendedor FROM vendedores v WHERE NOT EXISTS ( SELECT p.id_vendedor FROM pedidos p WHERE v.id = p.id_vendedor) ;
-- Ejercicio 2 --